name: "CI"

on:
    push:
        branches:
            - "development"
    pull_request:
        types:
            - "opened"
            - "synchronize"

jobs:
    ci:
        name: "Continuous Integration"
        runs-on: "self-hosted"

        steps:
            - name: "Checkout"
              uses: "actions/checkout@v4"
              with:
                  fetch-depth: 2

            - name: "Build"
              run: "make"

            - name: "Tests"
              run: "./build/rere replay ./test/*.list"


