name: "CI"

on:
    push:
        branches:
            - "main"
    pull_request:
        types:
            - "opened"
            - "synchronize"

jobs:
    ci:
        name: "Continuous Integration"
        runs-on: "ubuntu-latest"

        steps:
            - name: "Checkout"
              uses: "actions/checkout@v4"
              with:
                  fetch-depth: 2

            - name: "Build & Test"
              run: "make test"


